### ISSUE TITLE
Update references to ./OpenTabletDriver/Configurations

### ISSUE THREAD

**Issue by X9VoiD** [OpenTabletDriver/OpenTabletDriver.Packaging#5]
Configurations are now moved to `OpenTabletDriver.Configurations/Configurations`.

Updated packaging scripts:
- [ ] Debian
- [ ] Linux
- [ ] MacOS
- [ ] Redhat
- [ ] Windows
- [ ] Meta-packaging script ([base](https://github.com/OpenTabletDriver/OpenTabletDriver.Packaging/blob/master/base))

**Comment by hwsmm** [comment]
I think this is now resolved with 0.6.0 release?

**Comment by gonX** [comment]
Yes I can confirm all 6 are updated. This issue is resolved with all checkboxes checked.
